name: "Build the README"

on:
  schedule:
    # Run at 2:30 am
    - cron: "30 2 * * *"
  push:
  workflow_dispatch:
  repository_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: "Build the README"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
          show-progress: false

      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.9"

      - name: "Install dependencies"
        run: |
          python -m pip install -r requirements.pip

      - name: "Cog README"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          HACHYDERM_TOKEN: "${{ secrets.HACHYDERM_TOKEN }}"
        run: |
          python -m cogapp -rP README.md

      - name: "Commit and push if changed"
        # The timestamp line always changes.  
        # Only commit if more than one line changed.
        run: |
          if (( $(git diff --numstat README.md | cut -f 1) > 1)); then
            git diff
            git config user.name README-bot
            git config user.email actions@users.noreply.github.com
            git commit -am "Updated README"
            git push
          fi
