name: "Build the README"

on:
  schedule:
    # Run at 2:30 am
    - cron: "30 2 * * *"
  push:
  workflow_dispatch:
  repository_dispatch:

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    name: "Build the README"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write  # the Commit step needs to write updated README to the repo

    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v5"
        with:
          fetch-depth: 0
          show-progress: false
          persist-credentials: false

      - name: "Set up Python"
        uses: "actions/setup-python@v6"
        with:
          python-version: "3.9"

      - name: "Install dependencies"
        run: |
          python -m pip install -r requirements.pip

      - name: "Cog README"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m cogapp -rP README.md

      - name: "Commit and push if changed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # The timestamp line always changes.
        # Only commit if more than one line changed.
        run: |
          if (( $(git diff --numstat README.md | cut -f 1) > 1)); then
            git diff
            git config user.name README-bot
            git config user.email actions@users.noreply.github.com
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
            git commit -am "Updated README"
            git push
          fi
